modLoader = "javafml"
loaderVersion = "[${loaderVersion},)"
license = "LGPL-3.0"

[[mods]]
modId = "moremcmeta_json_parser_plugin"
version = "${modVersion}"
displayName = "MoreMcmeta JSON Parser Plugin"
authors = "soir20"
description = '''
Default plugin for MoreMcmeta that reads JSON (.moremcmeta) metadata files.
'''
logoFile="moremcmeta-logo-gradient.png"

[[dependencies.moremcmeta_json_parser_plugin]]
modId = "moremcmeta"
mandatory = true
versionRange = "[${minMoreMcmetaVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.moremcmeta_json_parser_plugin]]
modId = "forge"
mandatory = true
versionRange = "[${loaderVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moremcmeta_json_parser_plugin]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"